export const FETCH_PRODUCT_BEGIN = "FETCH_PRODUCT_BEGIN"
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS"
export const FETCH_PRODUCT_FAILURE = "FETCH_PRODUCT_FAILUREE"
export const ADD_TO_CART = 'ADD_TO_CART'
export const DELETE_FROM_CART = 'DELETE_FROM_CART'
export const SUB_QUANTITY = 'SUB_QUANTITY'
export const ADD_QUANTITY = 'ADD_QUANTITY'